root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ./cmd/server/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  delay = 1000

[log]
  time = true